#include "../Engine/Layers/language_model.h"
#include "../Engine/Tokenizer/bpe_tokenizer.h"

#include <iostream>
#include <string>
#include <vector>

int main() {
    std::cout << "========================================\n";
    std::cout << "RUSSIAN LM GENERATION TEST\n";
    std::cout << "========================================\n\n";

    const std::string MODEL_PATH =
        "../Models/Russian_best";

    const std::string TOKENIZER_PATH =
        "../Models/RussianTokenizer";

    const size_t VOCAB_SIZE = 16000;
    const size_t EMBED_DIM = 128;
    const size_t BLOCKS = 4;
    const size_t HEADS = 4;
    const size_t HIDDEN = 512;

    const int MAX_NEW_TOKENS = 60;

    // --------------------------------------------------------
    // Tokenizer
    // --------------------------------------------------------

    std::cout << "Loading tokenizer...\n";

    BPETokenizer tokenizer;
    tokenizer.Load(TOKENIZER_PATH);

    std::cout << "Vocabulary: "
              << tokenizer.GetVocabSize()
              << "\n\n";

    // --------------------------------------------------------
    // Model
    // --------------------------------------------------------

    std::cout << "Creating model...\n";

    LanguageModel model(
        VOCAB_SIZE,
        EMBED_DIM,
        BLOCKS,
        HEADS,
        HIDDEN,
        Device::CUDA
    );

    std::cout << "Loading model...\n";

    model.LoadModel(MODEL_PATH);

    std::cout << "Model loaded.\n\n";

    // --------------------------------------------------------
    // Prompts
    // --------------------------------------------------------

    std::vector<std::string> prompts = {
        "Он вошёл в комнату и",
        "— Послушай, я хотел тебе сказать, что",
        "Наступил вечер, и город"
    };

    for (const std::string& prompt : prompts) {

        std::cout << "----------------------------------------\n";
        std::cout << "PROMPT:\n";
        std::cout << prompt << "\n\n";

        // ----------------------------------------------------
        // Encode
        // ----------------------------------------------------

        std::vector<size_t> tokens =
            tokenizer.Encode(prompt);

        std::cout << "Prompt tokens: "
                  << tokens.size()
                  << "\n";

        if (tokens.empty()) {
            std::cout << "No tokens generated by tokenizer.\n";
            continue;
        }

        // ----------------------------------------------------
        // Generate
        // ----------------------------------------------------

        std::cout << "Generating...\n";

        std::vector<size_t> generated =
            model.generate(
                tokens,
                MAX_NEW_TOKENS,
                1.0f,     // temperature
                0.9f,     // top_p
                -1        // no EOS
            );

        // ----------------------------------------------------
        // Decode
        // ----------------------------------------------------

        std::string generated_text =
            tokenizer.Decode(generated);

        std::cout << "\nGENERATED:\n";
        std::cout << prompt << generated_text << "\n\n";

        std::cout << "Generated tokens: "
                  << generated.size()
                  << "\n";
    }

    std::cout << "\n========================================\n";
    std::cout << "TEST FINISHED\n";
    std::cout << "========================================\n";

    return 0;
}